import Riskmeter from "./Riskmeter";
import ThreatIndicators from "./ThreatIndicators";
import Recommendations from "./Recommendations";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { motion } from "framer-motion";

function ResultCard({ result, darkMode }) {

  if (!result || !result.prediction) {
    return (
      <div className="result-card empty-card">
        <h2
          style={{
            color: darkMode ? "#fff" : "#111827",
          }}
        >
          AI Threat Report
        </h2>

        <p
          style={{
            color: darkMode ? "#CBD5E1" : "#64748B",
          }}
        >
          Run an analysis to view AI insights.
        </p>
      </div>
    );
  }

  const status = result.prediction?.toUpperCase() || "SAFE";

  const statusClass =
    status === "PHISHING"
      ? "danger"
      : status === "SUSPICIOUS"
      ? "warning"
      : "safe";

      const downloadReport = () => {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
doc.setFontSize(22);
doc.text("AI Email Threat Detection Report", 14, 20);

doc.setFont("helvetica", "normal");

const reportId =
  "REP-" +
  new Date().getFullYear() +
  String(new Date().getMonth() + 1).padStart(2, "0") +
  String(new Date().getDate()).padStart(2, "0") +
  "-" +
  Math.floor(Math.random() * 9000 + 1000);

doc.setFontSize(10);

doc.text(`Report ID: ${reportId}`, 145, 18);
doc.text(`Generated: ${new Date().toLocaleString()}`, 145, 24);
doc.text("Engine: Gemini AI + Rule Engine", 145, 30);
doc.text("Version: 1.0", 145, 36);
  autoTable(doc, {
    startY: 45,
    head: [["Field", "Value"]],
    body: [
      ["Prediction", result.prediction],
      ["Confidence", result.confidence + "%"],
      ["Risk Score", result.risk_score + "%"],
      ["Overall Risk", result.summary_card?.overall_risk || "-"],
      ["Reason", result.summary_card?.reason || "-"],
      ["Action", result.summary_card?.action_required || "-"],
      ["Sender", result.email_data?.sender || "-"],
      ["Subject", result.email_data?.subject || "-"],
      ["Domain", result.email_data?.domain || "-"],
    ],
  });

  doc.setFont("helvetica", "bold");
doc.setFontSize(16);

doc.text(
  "AI Security Explanation",
  14,
  doc.lastAutoTable.finalY + 15
);

doc.setFont("helvetica", "normal");
doc.setFontSize(11);

let y = doc.lastAutoTable.finalY + 25;

if (Array.isArray(result.explanation)) {
  result.explanation.forEach((point) => {
    const lines = doc.splitTextToSize("• " + point, 180);
    doc.text(lines, 14, y);
    y += lines.length * 7;
  });
} else {
  const explanation = doc.splitTextToSize(
    result.explanation || "",
    180
  );
  doc.text(explanation, 14, y);
}
  doc.setFontSize(14);
doc.text("Email Authentication", 14, y + 10);

autoTable(doc, {
  startY: y + 18,

  head: [["Authentication", "Status"]],

  body: [
    ["SPF", result.header_analysis?.spf || "N/A"],
    ["DKIM", result.header_analysis?.dkim || "N/A"],
    ["DMARC", result.header_analysis?.dmarc || "N/A"],
    ["Authenticity", result.header_analysis?.authenticity || "Unknown"],
  ],

  theme: "striped",

  alternateRowStyles: {
    fillColor: [245, 245, 245],
  },

  styles: {
    fontSize: 10,
    cellPadding: 3,
  },
  didParseCell: function (data) {
  if (data.row.index === 3) {
    data.cell.styles.fillColor = [245, 245, 245];
  }
},
});
let threatY = doc.lastAutoTable.finalY + 8;
if (threatY > 220) {
  doc.addPage();
  threatY = 20;
}

doc.text("Threat Indicators", 14, threatY);
autoTable(doc, {
  startY: threatY + 5,

  

  head: [["Indicator", "Value", "Indicator", "Value"]],

  body: [
    [
      "Prediction",
      result.prediction || "-",
      "Confidence",
      (result.confidence || 0) + "%"
    ],
    [
      "Risk Score",
      (result.risk_score || 0) + "%",
      "Overall Risk",
      result.summary_card?.overall_risk || "-"
    ]
  ],

  theme: "grid",

  headStyles: {
    fillColor: [33, 150, 243],
    textColor: 255
  },

  styles: {
    fontSize: 10,
    cellPadding: 3,
    halign: "center"
  }
});
doc.setFontSize(14);
doc.text(
  "Security Recommendations",
  14,
  doc.lastAutoTable.finalY + 8
);

autoTable(doc, {
  startY: doc.lastAutoTable.finalY + 15,
  head: [["Recommendation"]],
  body: result.recommendations.map(item => [item]),
  theme: "grid",
  styles: {
    fontSize: 10,
    cellPadding: 3,
  },
  headStyles: {
    fillColor: [33, 150, 243],
    textColor: 255,
  },
});

doc.setFontSize(10);
doc.setTextColor(120);

doc.text(
  "Generated by AI Email Threat Detection System | TMen Internship Project",
  14,
  285
);

  doc.save("AI_Email_Report.pdf");
};

  return (
    <motion.div
      className="result-card"
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >

      <h2
  style={{
    color: darkMode ? "#ffffff" : "#111827",
    textAlign: "center",
    marginBottom: "25px",
  }}
>
  Threat Intelligence Report
</h2>

      <div className={`status ${statusClass}`}>
        {result.prediction}
      </div>

      {/* ================= TOP ROW ================= */}

      <div className="top-row">

        <div className="info-box">

          <h3>📧 Email Information</h3>

          <p>
            <strong>Sender:</strong>{" "}
            {result.email_data?.sender || "Unknown"}
          </p>

          <p>
            <strong>Subject:</strong>{" "}
            {result.email_data?.subject || "Unknown"}
          </p>

          <p>
            <strong>Domain:</strong>{" "}
            {result.email_data?.domain || "Unknown"}
          </p>

          <p>
            <strong>Date:</strong>{" "}
            {result.email_data?.date || "Unknown"}
          </p>

        </div>

        <div className="info-box risk-box">

          <Riskmeter
            prediction={result.prediction}
            confidence={result.confidence}
            risk_score={result.risk_score}
            darkMode={darkMode}
          />

        </div>

      </div>

      {/* ================= SUMMARY ROW ================= */}

      <div className="summary-row">

        <div
  className="info-box summary-box"
  style={{
    borderLeft:
      status === "PHISHING"
        ? "5px solid #ef4444"
        : status === "SUSPICIOUS"
        ? "5px solid #f59e0b"
        : "5px solid #22c55e",
  }}
>
  <h3>📊 Executive Summary</h3>

  <p>
    <strong>Overall Risk:</strong>{" "}
    {result.summary_card?.overall_risk || "Unknown"}
  </p>

  <p>
    <strong>Primary Trigger:</strong>{" "}
    {result.summary_card?.reason || "N/A"}
  </p>

  <p>
    <strong>Action Required:</strong>{" "}
    {result.summary_card?.action_required || "No action required"}
  </p>
</div>

<div className="info-box">

  <h3>📝 AI Security Explanation</h3>

  {Array.isArray(result.explanation) ? (
  <ul style={{ paddingLeft: "20px", lineHeight: "1.8" }}>
    {result.explanation.map((point, index) => (
      <li key={index}>{point}</li>
    ))}
  </ul>
) : (
  <p>{result.explanation}</p>
)}

</div>

</div>

<div
  style={{
    display: "flex",
    justifyContent: "center",
    marginTop: "30px",
    marginBottom: "30px",
  }}
>
  <button
    className="analyze-btn"
    onClick={downloadReport}
    style={{
      width: "340px",
    }}
  >
    🛡️ Download Security Analysis Report
  </button>
</div>

{/* ================= MIDDLE ROW ================= */}

<div className="middle-row">

  <div className="info-box authentication-box">

    <h3>🔐 Email Authentication</h3>

    <div
      style={{
        display: "flex",
        gap: "10px",
        flexWrap: "wrap",
        marginTop: "15px",
      }}
    >

      <span
        className={`badge ${
          result.header_analysis?.spf === "PASS"
            ? "pass-class"
            : "fail-class"
        }`}
      >
        SPF : {result.header_analysis?.spf || "NONE"}
      </span>

      <span
        className={`badge ${
          result.header_analysis?.dkim === "PASS"
            ? "pass-class"
            : "fail-class"
        }`}
      >
        DKIM : {result.header_analysis?.dkim || "NONE"}
      </span>

      <span
        className={`badge ${
          result.header_analysis?.dmarc === "PASS"
            ? "pass-class"
            : "fail-class"
        }`}
      >
        DMARC : {result.header_analysis?.dmarc || "NONE"}
      </span>

    </div>

    <p style={{ marginTop: "15px" }}>
      <strong>Authenticity:</strong>{" "}
      {result.header_analysis?.authenticity || "Unknown"}
    </p>

  </div>

  <div className="info-box">

    <h3>📧 Email Header Details</h3>

    <div className="header-grid">

      <div className="header-item">
        <strong>Sender</strong>
        <p>{result.email_data?.sender || "Unknown"}</p>
      </div>

      <div className="header-item">
        <strong>Subject</strong>
        <p>{result.email_data?.subject || "Unknown"}</p>
      </div>

      <div className="header-item">
        <strong>Domain</strong>
        <p>{result.email_data?.domain || "Unknown"}</p>
      </div>

      <div className="header-item">
        <strong>Date</strong>
        <p>{result.email_data?.date || "Unknown"}</p>
      </div>

    </div>

  </div>

</div>
{result.statistics?.urls > 0 && (
  <div className="info-box url-audit-box">

    <h3>🔗 URL Security Audit</h3>

    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(4,1fr)",
        gap: "12px",
        marginTop: "15px",
      }}
    >

      <div className="audit-card">
        <h4>{result.url_scanned_details?.safe_urls?.length || 0}</h4>
        <span>Safe</span>
      </div>

      <div className="audit-card">
        <h4>{result.url_scanned_details?.suspicious_urls?.length || 0}</h4>
        <span>Suspicious</span>
      </div>

      <div className="audit-card">
        <h4>{result.url_scanned_details?.shortened_urls?.length || 0}</h4>
        <span>Shortened</span>
      </div>

      <div className="audit-card">
        <h4>{result.url_scanned_details?.ip_urls?.length || 0}</h4>
        <span>IP Based</span>
      </div>

    </div>

    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        marginTop: "18px",
        color: "#94a3b8",
        fontSize: "14px",
      }}
    >
      <span>Total URLs: {result.statistics?.urls}</span>
      <span>Email IDs: {result.statistics?.email_addresses}</span>
      <span>Phone Numbers: {result.statistics?.phone_numbers}</span>
    </div>

  </div>
)}

{/* ================= THREAT INDICATORS ================= */}

<ThreatIndicators
    result={result}
    darkMode={darkMode}
/>

{/* ================= RECOMMENDATIONS ================= */}

<Recommendations
  prediction={result.prediction}
  recommendationsList={result.recommendations}
/>

</motion.div>
);
}

export default ResultCard;

